### ISSUE TITLE
DSP Incomplete/Undocumented

### ISSUE THREAD

**Issue by TkTech** [amzn/ads-advanced-tools-docs#231]
**Describe the bug**
Recently added DSP v3 reports do not appear to work, or they are not properly documented.

Attempting to make a request can't succeed, because it both requires adProduct, and must not have an adProduct when trying to get dspInventory report.

If you do not provide an `adProduct`:

```
{'code': '400', 'detail': 'Required fields are invalid or missing: configuration adProduct'}
```

If you provide an `adProduct` (which does not have a value defined under enums for DSP)

```
{'code': '400', 'detail': 'configuration adProduct is not supported for this report type'}
```

**URL of the content**
https://advertising.amazon.com/API/docs/en-us/guides/reporting/v3/report-types/inventory

**Description of what the documentation currently says**

Nothing, page is effectively blank.

**Description of what the documentation should say**

If this report does not follow the usual reporting pattern of v3, it should be documented, and an example of how to use it provided. Enums for adProduct should be updated to include value for dsp reports.

Possible group bys documented at top summary do not match actual possible group by values, llke `supplySource`.

**Comment by glmcmull** [comment]
Hi @TkTech 

This is fixed, please see the adProduct value for DSP in the 'configuration' object: https://advertising.amazon.com/API/docs/en-us/offline-report-prod-3p#tag/Reports/operation/getCampaignReportV3

**Comment by TkTech** [comment]
Thanks @glmcmull. Still appear to be several errors in the documentation.

For example, this claims the valid group by clauses are campaign, ad, or creative, and there are many possible groupBy clauses listed farther down the page.

![image](https://github.com/amzn/ads-advanced-tools-docs/assets/72590/99ce701e-b39b-41ca-b1f6-aca21ec84169)

However, in reality it appears only two work:

```
{'code': '400', 'detail': 'configuration The dspInventory reports requires either site or supplySource as a groupBy'}
```

**Comment by glmcmull** [comment]
This will be addressed soon along with some other fixes.

**Comment by TkTech** [comment]
Thanks for the update @glmcmull, fantastic! :)
